# docker-compose.yml

version: '3.9'

services:
  web:
    build: .
    command: gunicorn mygamesite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gamesite
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A mygamesite worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
